### PR TITLE
[TIMOB-19681] Android: Recompiled Ti.Map with NDK r10e

### PR DESCRIPTION
**Pull request by ashcoding**
Jira: https://jira.appcelerator.org/browse/TIMOB-19681

### CODE REVIEW

**Comment by ashcoding** [comment]
To test, checkout this PR and install mobile module android/dist/ti.map-android-2.3.4.zip into a sample app as mention in Jira Ticket.

**Comment by sriks** [comment]
Tested. Approved.

**Comment by ashcoding** [comment]
**Merging**

**Comment by hieupham007** [comment]
Please update the changelog whenever you up the map version.

**Comment by ashcoding** [comment]
Noted and thanks!

**Pull request merged**
