### PR TITLE
[MOD-2268] and [MOD-2285] - Support property "hidden" of Marker and "opacity" of MKCircle and more

### PR DESCRIPTION
**Pull request by hansemannn**
Cherry picked some changes from #178. This fixes [MOD-2268](https://jira.appcelerator.org/browse/MOD-2268) and [MOD-2285](https://jira.appcelerator.org/browse/MOD-2285)

- [x] Fixed docs
- [x] Exposed `hidden` property for annotations for iOS and Android
- [x] Updated license headers
- [x] Removed old `MapiOS7View` class
- [x] Grouped iOS source-files properly
- [x] Expose dynamic annotation colors, add missing parity colors
- [x] Fixed deprecations

Please use our example files in `ios/example/` and `android/example` to test this. The primary tests should go around the circle, annotation and mapview. Let me know if specific tests-casts are needed. P.S.: The android-changes have already been approved by me, so the primary review should go to the iOS changes I did to fix certain other stuff.

### CODE REVIEW

**Comment by hansemannn** [comment]
@vijaysingh-axway We require iOS 7 since 2 years (and iOS 8 since Titanium SDK 6) :-) So there won't be any dev using this module for iOS < 7. Besides that, the snippet comes from a time where the sub-views have been included instead of being required, making the "top" property global. So it didn't take affect since release 2.0. I will remove the snippet and check the other demo-code for references.

**Comment by vijaysingh-axway** [comment]
1. If we do not pass opacity, circle is not visible. It should take default as 1.0 .
2. circleRenderer.alpha = isnan(alpha) ? 1 : alpha;
  Rather 1 we should make it 1.0, as we are taking float .

**Comment by hansemannn** [comment]
This is interesting. So `isnan(alpha)` returns `NO` and tries to apply the `alpha` default value? Will set a default value in the constructor and go from there.

**Comment by hansemannn** [comment]
Cleaned everything up and added the default values (check the latest commit please) 🚀

**Comment by vijaysingh-axway** [comment]
@hansemannn  ,
Opacity related issue get resolved. Its fine now.

I Think you have missed my first comment --

"-(void)setVisible:(id)value -
If set value of visible by this function, annotation do not show/hide . Though value of property changed .I think refresh is not happening properly . If we assign property while creating , it will show its effect. I have added a Tests case example in Ticket ."

Please check the same.

**Comment by hansemannn** [comment]
Hey @vijaysingh-axway, sorry for the delay. So it turns out we cannot use "visible" on iOS, because it's already "owned" by the underlaying TiProxy. But we also cannot use that one, because it would not trigger the annotation update. So I decided to rename it to "hidden" for both platforms and go with that instead (inverted, false by default). Since it's a new property, it should be fine to use by people. Thx!

**Comment by hansemannn** [comment]
I guess the "visible" getter in your example was still used. I updated the example in our JIRA ticket. And I removed the "setVisible" from the header and replaced it with the "setHidden" one. Not required, but cleaner.

**Comment by vijaysingh-axway** [comment]
@hansemannn @ewieberappc , I am not able to assign reviewer and add label in this PR. If you guys have permission for same , please do that.

**Comment by ewieberappc** [comment]
@hansemannn @vijaysingh-axway, when testing on iOS I noticed a couple of issues:
1. Opacity can be set with setOpacity() or circ.opacity, but can only be referenced with getAlpha() or circ.alpha. Looks like this was missed in the rename of alpha to opacity.
2. Opacity cannot be set on creation of the circle. Tried both alpha and opacity properties. It can be changed after creation, however. (you can use a hex color value for the fill with an alpha component present. This will appropriately SHOW the alpha value, but will not actually set the opacity/alpha)

**Comment by hansemannn** [comment]
Damn it, same problems as with the "visible" property. It's manual setter / getter are reserved to the proxy API, which won't work because annotations are no (public) UIView subclasses like usual views.  So we'd need to call it "alpha" instead, causing an issue with the parity of Android that uses "opacity" since 4.1.0. We could deprecate the Android one and unify them as "alpha", but there must be a better to solution. What do you think Eric?

**Comment by hansemannn** [comment]
Ok, fixed it. Explicit test-case for this one:
```js
var win = Ti.UI.createWindow({
    backgroundColor: '#fff'
});

var maps = require('ti.map')
 
var view = maps.createView({
    region: {
        latitude: 37.368122,
        longitude: -121.913653,
        latitudeDelta: 0.01,
        longitudeDelta: 0.01
    }
});

var circle = maps.createCircle({
    center: {
        latitude: 37.368122,
        longitude: -121.913653
    },
    fillColor: "red",
    opacity: 0.5,
    radius: 30
});

view.addCircle(circle);

// Change values after 2 seconds
setTimeout(function() {
    circle.opacity = 1.0;
    circle.fillColor = "green";
    
    // The radius and center is creation-only
}, 2000);

win.add(view);
win.open();
```

**Comment by hansemannn** [comment]
@vijaysingh-axway The circle-retain was used from the previous code and is necessary because it's called outside the current retain-scope. But I just pushed on update that removes the external access and replaces it by getting the circle through the circle renderer.

For the opacity, there are no manual getters, only the ones generated by the proxy once a setter is called. I've added a `replaceValue` call to ensure the updated are available to the proxy.

**Comment by hansemannn** [comment]
Test for circles:
```js
var maps = require('ti.map');

var win = Ti.UI.createWindow({
    backgroundColor: '#fff'
});

var mapView = maps.createView({
    region: {
        latitude: 37.368122,
        longitude: -121.913653,
        latitudeDelta: 0.5,
        longitudeDelta: 0.5
    }
});

var circle = maps.createCircle({
    center: {
        latitude: 37.368122,
        longitude: -121.913653,

    },
    opacity: 0.5,
    fillColor: "#f00",
    radius: 1000
});

Ti.API.info(circle.opacity);

mapView.addCircle(circle);

win.add(mapView);
win.open();
```

**Comment by hansemannn** [comment]
@vijaysingh-axway Ping

**Pull request merged**
