### PR TITLE
[TIMOB-18992] Add ti.map for Windows - WIP

### PR DESCRIPTION
**Pull request by garymathews**
###### WIP - DO NOT MERGE
- Add windows _ti.map_ projects
###### NOTES
- To compile run `generate.bat` and then run `ti build -p windows -G 00000000-0000-1000-8000-000000000000 --build-only`

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-18992)

### CODE REVIEW

**Comment by hansemannn** [comment]
Hey @garymathews, where are we here? Would be cool to have this in for parity.

**Comment by hansemannn** [comment]
@garymathews @infosia What's up with this? Should I close it? Can we merge it?

**Comment by hansemannn** [comment]
Closing for now to keep the open PR's clean, please feel free to reopen as soon as we consider this change again. Thx!

**Comment by hansemannn** [comment]
@infosia Ping! 😙

**Comment by infosia** [comment]
@hansemannn Please close this for now, this one is too old.  :goberserk:

**Pull request closed without merging**
