### PR TITLE
MOD-2617: Added UT's for TiMapView Public methods

### PR DESCRIPTION
**Pull request by anil-shukla-axway**
https://jira.appcelerator.org/browse/MOD-2617

### CODE REVIEW

**Comment by fasihul-axway** [comment]
@anil-shukla-axway, its better to add a describe tag which can tell wether UT is for methods, property or constraint. Something like

`describe('methods', () => { }`

**Comment by fasihul-axway** [comment]
Also, i am not sure if all properties and methods are covered, please check once again and if any missing add them.

https://github.com/appcelerator-modules/ti.map/blob/master/ios/Classes/TiMapView.h

**Comment by anil-shukla-axway** [comment]
> @anil-shukla-axway, its better to add a describe tag which can tell wether UT is for methods, property or constraint. Something like
> 
> `describe('methods', () => { }`

Done

**Comment by anil-shukla-axway** [comment]
> Also, i am not sure if all properties and methods are covered, please check once again and if any missing add them.
> 
> https://github.com/appcelerator-modules/ti.map/blob/master/ios/Classes/TiMapView.h

As we discussed, we will be creating one separate task for the same.

**Comment by sgtcoolguy** [comment]
manually rebased, cleaned up and merged to master

**Pull request closed without merging**
