### PR TITLE
[MOD-2345] iOS: Add parity for "padding" on MapView, use dictionary on Android

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA**: https://jira.appcelerator.org/browse/MOD-2345

### CODE REVIEW

**Comment by hansemannn** [comment]
Hey @garymathews! I just merged #206 that you approved earlier, not noticed it has an unusual parameter structure (4 parameters instead of one dictionary). I changed that and also added iOS parity. The modules build fine, but can you still do a CR for the changes?

**Comment by designbymind** [comment]
What's up, @hansemannn & @garymathews? — is there an approximate date planned to merge this PR? Also, will `padding` and/or `setPadding()` take a dictionary? (for use in iOS) ---> Thanks! 🗺️

**Comment by hansemannn** [comment]
@designbymind The Android team has more critical work to do right now, but please feel free to grab the PR and build the module as needed. It does include a dictionary-based API for passing left/top/right/bottom args.

**Comment by designbymind** [comment]
@hansemannn right on. Thanks for he update! — I compiled 3.1.0 for iOS about a week ago and tried setting padding in both stylesheet (TSS) & controller (.js) with no success. Maybe I'm missing something, not sure. It's not feature I currently _need_, but when it does work, it will be nice to move elements like the scale/compass to fit custom map UI's. Below is a summary of what I've tested for **iOS Ti.Map** `3.1.0`

**tss:**
```
'#mapView' : {
    width: Ti.UI.FILL,
    height: Ti.UI.FILL,
    padding: {
        left: 0,
        top: 200,
        right: 0,
        bottom: 200
    },
    rotateEnabled: true,
    pitchEnabled: true,
    showsScale: true,
    compassEnabled: true
}
```
**js:**
```
$.mapView.setPadding({
    left: 0,
    top: 200,
    right: 0,
    bottom: 200
});
```
The controller being more important as it will allow for iPhone X conditionals, etc.

P.S. — I have not tested Android as that's not my current area of focus at this time.

**Comment by hansemannn** [comment]
It looks like MapKit, the framework behind Ti.Map iOS is currently in a bad state: https://stackoverflow.com/a/48736678/5537752. Per native documentation, it should affect the visible map rectangle. You could try replacing the current API `setVisibleMapRect:edgePadding:animated:` with `setLayoutMargins:`

**Comment by designbymind** [comment]
@hansemannn as suggested, I created a [PR](https://github.com/appcelerator-modules/ti.map/pull/253) to use `layoutMargins` 🙃

**Pull request merged**
