### PR TITLE
[DOC] : Map route doc updated

### PR DESCRIPTION
**Pull request by vijaysingh-axway**
https://docs.appcelerator.com/platform/latest/#!/api/Modules.Map.Route

### CODE REVIEW

**Comment by vijaysingh-axway** [comment]
@jawa9000 In doc specification  default should be  mentioned as below -
     default: <Modules.Map.OVERLAY_LEVEL_ABOVE_LABELS>
But in document if I see this link is missing. So I checked YAML file in api docs and found at couple of places default is written as -
    default: Modules.Map.OVERLAY_LEVEL_ABOVE_LABELS
And this link is available in document.  So I have changed to the second style.

I guess doc specification needs to updated. Thanks!

**Comment by vijaysingh-axway** [comment]
broken_link

If you see the default value of level property, it is showing  "", no link. For this property default is written as -
default: <Modules.Map.OVERLAY_LEVEL_ABOVE_LABELS> in YAML file.

Similar issue with some other properties as well. E.g. -
If you see 'keyboardAppearance' and 'keyboardType' properties of Titanium.UI.TextField.
https://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.TextField.
The link with default is missing. It is showing "" only.
Though in YAML doc default is written as  -

    default: <Titanium.UI.KEYBOARD_APPEARANCE_DEFAULT>

    default: <Titanium.UI.KEYBOARD_TYPE_DEFAULT>
respectively.

I think there is some problem in converting default value to link in doc. Thanks!

**Comment by hansemannn** [comment]
It may be that links (that are usually indeed in that format) are not resolved by the docgen correctly, if they do not prefix with `Titanium`. @vijaysingh-axway / @jawa9000  can you look into the docgen to verify that?

**Comment by hansemannn** [comment]
PR rejected for now. The `MapPointType` type-definition is already present in the `ImageOverlay.yml` and the brackets are required for proper linking. I hope a follow-up ticket will be created to fix the doc-gen regarding that.

**Pull request closed without merging**
