### PR TITLE
[TIMOB-9403] Add centerOffset-property handling for Android map annotations.

### PR DESCRIPTION
**Pull request by ndob**
This pull request adds handling for centerOffset-property on Map.Annotation-objects. 
Relevant JIRA-ticket: https://jira.appcelerator.org/browse/TIMOB-9403

This should work as the corresponding iOS-feature: offset is in pixels, positive values move down and right. [1]

Only open issue is, that when centerOffset-property is not set, Android uses the default anchor, which points to horizontal center and vertical bottom [2]. I didn't dare to break the existing functionality by defaulting to horizontal and vertical center, but comments regarding to this are of course welcome.

[1] https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKAnnotationView_Class/index.html#//apple_ref/occ/instp/MKAnnotationView/centerOffset
[2] https://developer.android.com/reference/com/google/android/gms/maps/model/Marker.html

### CODE REVIEW

**Comment by ndob** [comment]
Is it possible to get this merged?

**Comment by mrlundis** [comment]
@ndob Thank you for implementing this, you just saved the better par of my day! :)

A small heads up though: with the current implementation the centerOffset point needs to be set in system units, even if you use another unit (e.g. dips) as the default unit.

**Comment by ingo** [comment]
Can you please add documentation to https://github.com/appcelerator-modules/ti.map/blob/master/apidoc/Annotation.yml#L61?

**Comment by ndob** [comment]
@mrlundis Great to hear. :) The offset is currently in pixels, because in iOS documentation (link number 1) it says: "This x and y offset values are measured in pixels.". So this should be in parity with that.

@ingo I added Android-platform to the documentation now.

**Comment by yozef** [comment]
This would be nice to have in the next ti.map, if you can look into the conflict

**Comment by yozef** [comment]
I manually implemented your changed into my Ti.Map version.

using this: 
~~~
var markerLocation = Map.createAnnotation({
    image:'/images/markerPin.png', centerOffset: {x:50, y:70} // didn't do anything. 
});
~~~
markerPin.png 's size is: 100 x 135, so I'm guessing {x:50, y:70} gets the center of the image?

Even with this, the Pin is exactly where it used to be, middle / bottom of Image

**Comment by ndob** [comment]
Is there something preventing the merge of this PR?

**Comment by yozef** [comment]
I've actually reimplemented your code in my version of Ti.Map for Android, and it does the job.

**Comment by williamrijksen** [comment]
@ingo Can you take a look at this PR? I resolved the merge conflicts about this PR. The errors occurring in Travis, but i don't know the exact reason.

**Comment by williamrijksen** [comment]
Ready for review!

**Comment by ashcoding** [comment]
@williamrijksen I'll be happy to review this. Travis seems to be passing.

**Comment by ashcoding** [comment]
@williamrijksen could you write a sample app/test for the PR? That would help greatly.

Also could you rebase this branch? We just merged a commit and this seems to have made ur branch to be in conflict.

**Comment by williamrijksen** [comment]
@ashcoding merge conflict solved

**Comment by williamrijksen** [comment]
@ashcoding Because you asked my to write a sample app, i wrote that one. You can find it here: https://github.com/williamrijksen/TiMapsSample. It's still necessary to set you own Google maps-key to do a functional test.

To clarify what is happening I'll insert two screenshots. One with a default annotation and one with a set `centerOffset` property.
1. Default
screenshot_2015-10-30-14-01-51

2. With `centerOffset: {x:0,y:0}`
screenshot_2015-10-30-14-02-09

If you have any questions, don't hesitate to ask them.

**Comment by williamrijksen** [comment]
@ashcoding See the difference:
1. Default: https://github.com/williamrijksen/TiMapsSample/blob/master/app/controllers/defaultMap.js#L6.
2. With Centeroffset:https://github.com/williamrijksen/TiMapsSample/blob/master/app/controllers/centerOffsetMap.js#L9.

**Comment by ashcoding** [comment]
@williamrijksen would handling offset changes in the `onPropertyChanged` https://github.com/appcelerator-modules/ti.map/pull/79/files#diff-f3c99af2a7979e334ec513288183b11cR318 be required as well?

**Comment by williamrijksen** [comment]
@ashcoding I tried to handle the offset changes in the `propertyChanged`, but the view didn't update. I think it's the same issue as https://jira.appcelerator.org/browse/TIMOB-19543.

**Comment by ashcoding** [comment]
@williamrijksen Okay. Understand where you're coming from. :)

**Comment by jvandijk** [comment]
@ashcoding @hansemannn please have a look at this PR again. I've just updated the merged master into it to make it completely in sync again.
We are already using this in production quite a while.

**Comment by hansemannn** [comment]
LGTM. @ashcoding has the final decision here.

**Comment by ashcoding** [comment]
It looks good but I'm having trouble making the offset work. I'm getting both images look like the default. 

@hansemannn are you able to functionally test it out?

**Comment by williamrijksen** [comment]
@ashcoding @hansemannn What's the state of this PR?

**Comment by jvandijk** [comment]
@ashcoding see this example code as @williamrijksen provided: https://github.com/williamrijksen/TiMapsSample/blob/master/app/controllers/centerOffsetMap.js#L6

**Comment by ashcoding** [comment]
Tried it again. Works. I think I did something wrong earlier. In any case, works well. 👍

**Comment by ashcoding** [comment]
Code reviewed and functionally tested.
**Approved**

**Pull request merged**
