### PR TITLE
Fixed: App crashing when the the map is being releases.

### PR DESCRIPTION
**Pull request by asiby**
I have accidentally included unrelated javascript typos fixes in the same commits.

### CODE REVIEW

**Comment by ashcoding** [comment]
PR is for #154

**Comment by ashcoding** [comment]
@asiby Awesome work! Could you include the code to that will reproduce the crash here in the comments to test this with?

**Comment by asiby** [comment]
Sure. But strangely enough, this test code stopped giving me the error. May the map is not properly being released anymore. But in addition to the "crash on release", this code also uncoveres another bug in ti.map that is 100% reproducible:

1. The map keep resetting its position (the region) if you move 2 or more pages away in the ScrollableView then go back to the map.
2. Touch a marker on the map, then page at least 2 screens away, then come back to the map, after noticing the strange behaviour at point 1 above, touching the same marker (or the last marker) that was initially touched will make the map crash.

Create an alloy project

**index.js**

```
var Map = require("ti.map");

var mapHolderView = "view1";

var anno = Map.createAnnotation({
	latitude : -33.87365,
	image : 'map_pin.png',
	longitude : 151.20689,
	title : "Sydney",
	subtitle : "Sydney is quite chill",
	draggable : true
});
var anno2 = Map.createAnnotation({
	latitude : -33.86365,
	pincolor : Map.ANNOTATION_GREEN,
	longitude : 151.21689,
	title : "Anno2",
	subtitle : "This is anno2",
	draggable : true
});
var anno3 = Map.createAnnotation({
	latitude : -33.85365,
	longitude : 151.20689,
	title : "Anno3",
	subtitle : "This is anno3",
	draggable : false
});
var anno4 = Map.createAnnotation({
	latitude : -33.86365,
	longitude : 151.22689,
	title : "Anno4",
	subtitle : "This is anno4",
	draggable : true
});

Ti.API.info("Latitude:" + anno.latitude);
Ti.API.info("Title:" + anno.title);

var map = Map.createView({
	userLocation : true,
	mapType : Map.NORMAL_TYPE,
	animate : true,
	annotations : [anno, anno2, anno3, anno4],
	region : {
		latitude : -33.87365,
		longitude : 151.20689,
		latitudeDelta : 0.1,
		longitudeDelta : 0.1
	}, //Sydney
	top : 10,
	left: 0,
	width: Ti.UI.FILL,
	height: Ti.UI.FILL
});

function releaseMap() {
	if (map != null) {
		map.removeAnnotations([anno, anno2, anno3, anno4]);
		anno = null;
		anno2 = null;
		anno3 = null;
		anno4 = null;
		$[mapHolderView].remove(map);
		map = null;
	}
	
	// Add something to all the pages to eventually tricky the garbage collector to release the map.
	for (var i = 1; i <= 9; i++) {
		$["view" + i].add(Ti.UI.createImageView({
			image: "https://placeholdit.imgix.net/~text?txtsize=33&txt=Test%20Image%20" + i + "&w=300&h=350",
			top: 20
		}));
	}
}

$[mapHolderView].add(map);

$.index.open();
```

**index.xml**

```
<Alloy>
	<Window class="container">
		<Button title="Release Map" onClick="releaseMap"></Button>
		<ScrollableView>
			<ScrollView scrollType="vertical" id="view1" class="page">
				<Label text="PAGE 1"></Label>
			</ScrollView>
			<ScrollView scrollType="vertical" id="view2" class="page">
				<Label text="PAGE 2"></Label>
			</ScrollView>
			<ScrollView scrollType="vertical" id="view3" class="page">
				<Label text="PAGE 3"></Label>
			</ScrollView>
			<ScrollView scrollType="vertical" id="view4" class="page map">
				<Label text="PAGE 4" backgroundColor="yellow"></Label>
			</ScrollView>
			<ScrollView scrollType="vertical" id="view5" class="page">
				<Label text="PAGE 5"></Label>
			</ScrollView>
			<ScrollView scrollType="vertical" id="view6" class="page">
				<Label text="PAGE 6"></Label>
			</ScrollView>
			<ScrollView scrollType="vertical" id="view7" class="page">
				<Label text="PAGE 7"></Label>
			</ScrollView>
			<ScrollView scrollType="vertical" id="view8" class="page">
				<Label text="PAGE 8"></Label>
			</ScrollView>
			<ScrollView scrollType="vertical" id="view9" class="page">
				<Label text="PAGE 9"></Label>
			</ScrollView>
		</ScrollableView>
	</Window>
</Alloy>
```

**index.tss**

```
".container": {
	backgroundColor:"white",
	layout: "vertical"
},

"ScrollableView": {
	top: 10
},

"Label": {
	width: Ti.UI.SIZE,
	height: Ti.UI.SIZE,
	color: "#000",
	top: 10
},

"#view1": {
	backgroundColor: "green"
},

"#view2": {
	backgroundColor: "yellow"
},

"#view3": {
	backgroundColor: "red"
},

"#view4": {
	backgroundColor: "purple",
	layout: "vertical"
},

"#view5": {
	backgroundColor: "blue"
},

"#view6": {
	backgroundColor: "orange"
},

"#view7": {
	backgroundColor: "brown"
},

"#view8": {
	backgroundColor: "teal"
},

"#view9": {
	backgroundColor: "gray"
},

".map": {
	width: Ti.UI.FILL,
	height: Ti.UI.FILL,
},

"Button": {
	top: 10
},

".page": {
	layout: "vertical"
}
```

**Comment by ashcoding** [comment]
@asiby That should because the view is being recreated/reinitialised when you scroll the page. To prevent this use `<ScrollableView cacheSize="9"> if you have 9 views to scroll. This will cache and store the views inside the ScrollableView and not recreate it when it scrolls away. Try it out and let me know if it works.

Point 2) sounds like a bad crash. That needs to be investigated.

Thanks for that detailed example code!

**Comment by asiby** [comment]
You are welcome.

Something is missing in your answer near ...

> To prevent this use `

**Comment by ashcoding** [comment]
Just edited it. :)

**Comment by asiby** [comment]
Thanks. I will try that right now.

**Comment by asiby** [comment]
The cache size property fixed the point number 1. So it is when the map view is recreated that clicking on the same point crashes the app because now that the scrollable view is caching the 9 views, I am not experiencing it in this particular case.

Thanks again

**Comment by ashcoding** [comment]
Glad that that fixed that issue. :+1:

**Comment by ashcoding** [comment]
The PR is to ensure a null check is done before clearing an object.
**Accepted**

**Pull request merged**
