### PR TITLE
[TIMOB-23269] Android: Fix Annotation memory leak

### PR DESCRIPTION
**Pull request by garymathews**
- Release annotation objects when removing annotations

###### TEST CASE
- Project in JIRA Ticket

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23269)

### CODE REVIEW

**Comment by yozef** [comment]
This commit crashes the app when you an addAnnotation (the same one twice) which used to be handled gracefully.

**Comment by fmerzadyan** [comment]
CR and FT PASS

**Comment by garymathews** [comment]
@yozef Thanks!

@fmerzadyan I've updated the PR

###### TEST CASE
```Javascript
var win = Ti.UI.createWindow(),
    Map = require('ti.map'),
    a = Map.createAnnotation({
        title: 'Appcelerator',
        latitude: 37.3680, longitude: -121.9145,
        pincolor: Map.ANNOTATION_GREEN
    }),
    map = Map.createView({
        userLocation: true,
        mapType: Map.NORMAL_TYPE,
        animate: true,
        annotations: [a],
        region: { // Appcelerator
            latitude: 37.3680, longitude: -121.9145,
            latitudeDelta: 0.1, longitudeDelta: 0.1
        }
    });

map.addAnnotation(a);

win.add(map);
win.open();
```

**Comment by hansemannn** [comment]
@yozef Does everything work for you now?

**Comment by hansemannn** [comment]
@garymathews So I talked to @yozef, it works for him. @fmerzadyan can you confirm and merge please? We want to get ti.map ready for 6.1.0, so I can update it on ti-master.

**Comment by fmerzadyan** [comment]
Looks good. Handing over to QE.

**Pull request merged**
