### PR TITLE
Android encoded polylines

### PR DESCRIPTION
**Pull request by AppWerft**
In polygonproxy, polylineproxy and routesproxy with this new version we can use encoded coords. This accelerates

### CODE REVIEW

**Comment by m1ga** [comment]
@AppWerft please run `clang-format -style=file -i [your-files]` to correct the styling of the files

**Comment by AppWerft** [comment]
done and pushed. 
Anything else to do?

**Comment by AppWerft** [comment]
This command has formatted a lot …

**Comment by m1ga** [comment]
> This command has formatted a lot …

yes, because you've changed a lot of the previous format in your initial commit e.g. `{` at the end of the functions etc.
You only did it to one file. Please do it for the other files you've changed too. The PR to check gets a lot smaller if you only see your changes.

And please add that feature to the documentation too (it is in the apidoc folder).

The .project file is not needed, please remove that.

And I don't mind the `android/idejars` inside the .gitignore but it is something very special to you since it is not a default folder. But since it is ignored its fine (but I'm not responsible for this repo :-) )

**Comment by AppWerft** [comment]
Whats about linting? apidoc I have updated, some files removed.

**Comment by m1ga** [comment]
`android/idejars/android-maps-utils-0.5.jar` is still there.
Linting should be fine now. You've linted files you've didn't touch but should be fine since they where un-linted before; that is why there are more files in your PR now

**Comment by AppWerft** [comment]
I think linting is OK and it isn't  a bad idea to start it over all files in folder. Or is there an issue I dont know?

**Comment by m1ga** [comment]
like I've said: it is correct. It is just harder for the reviewer to see your code since there are changes that are just because of indentation.  But it is not wrong! It's up to the reviewer to check it now :smile:

**Comment by AppWerft** [comment]
The old version was unlinted?

**Comment by m1ga** [comment]
just check the files you've commited. E.g. here: https://github.com/appcelerator-modules/ti.map/pull/276/files#diff-d2da3006990b9caea54e013700a97132 it will just remove an empty line. Some files where added before the clang was added or the rules changed. If noone touches that files they won't be linted until some does it :) It will still compile fine

**Comment by AppWerft** [comment]
Sorry for the effort.

**Comment by sgtcoolguy** [comment]
Hi @AppWerft ! I'm so sorry for the super-long delay in picking this PR up (and #278). I've cleaned up the commits, rebased them and plan to merge this in and push a new release. But before I can do that, it looks like you need to sign our CLA (Contributor License Agreement). Again, very sorry about the delay - I'll hold this PR and merge it in once the CLA is signed.

**Comment by AppWerft** [comment]
What I have to do?

**Comment by sgtcoolguy** [comment]
@AppWerft Looks like you signed it now? OK, I'm going to try and get this merged now. (And you shouldn't need to sign again for the other PR or contributions you make).

Thanks!

**Pull request merged**
