### PR TITLE
[MOD-2346] Add support for dashed and dotted polylines

### PR DESCRIPTION
**Pull request by AndreaVitale**
PR: https://jira.appcelerator.org/browse/MOD-2346

### CODE REVIEW

**Comment by hansemannn** [comment]
@AndreaVitale I think we are able to map all three keys of the `pattern` property to iOS as well. But we are also able to apply all of them to the other overlay-types (polygon and cycle), is this possible for Android as well? As much as I want this to be included in the module, it only makes sense if we can deliver the cross-platform experience here.

**Comment by hansemannn** [comment]
Added @garymathews for the Android review. Not sure if the changed libraries are necessary for this feature.

**Comment by lokeshchdhry** [comment]
@hansemannn , For IOS implementation, for me `DASHED` works fine but `DOTTED` shows `DASHED`.

```
var Map = require('ti.map');
 
var win = Ti.UI.createWindow();
var mapView = Map.createView({
    region: {
        latitude: 37.338208,
        longitude: -121.886329,
        latitudeDelta: 0.1,
        longitudeDelta: 0.1
    }
});
 
mapView.addPolyline(Map.createPolyline({
    strokeColor: 'red',
    points: [{
        latitude: 37.338208,
        longitude: -121.886329
    }, {
        latitude: 37.138208,
        longitude: -121.686329
    }],
    pattern: {
        type: Map.POLYLINE_PATTERN_DOTTED, // Aso try POLYLINE_PATTERN_DASHED
        gapLength: 20,
        // dashLength: 100
    }
}));

win.add(mapView);
win.open();
```

Studio Ver:     4.9.1.201707200100
SDK Ver:        6.2.0.v20170809112741
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.9
Appc CLI:       6.2.3
Ti CLI Ver:     5.0.14
Alloy Ver:      1.9.13
Node Ver:       6.10.1
Java Ver:       1.8.0_101
IOS Simulator: Iphone 7 IOS 10.3.1
ti.map:            2.11.0 local build

**Comment by hansemannn** [comment]
@lokeshchdhry The difference is in the detail: dotted has rounded corners, dashed has square ones. see this example:
simulator screen shot 10 08 2017 21 06 55

**Comment by lokeshchdhry** [comment]
FR Passed.

The `DOTTED` & `DASHED` polyline works as expected.

Studio Ver:     4.9.1.201707200100
SDK Ver:        6.2.0.v20170809112741
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.9
Appc CLI:       6.2.3
Ti CLI Ver:     5.0.14
Alloy Ver:      1.9.13
Node Ver:       6.10.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Pixel --- Android 7.1.1
                ⇨ google Nexus 5 --- Android 6.0.
IOS Simulator: Iphone 7 plus IOS 10.3.1

**Pull request merged**
