### PR TITLE
android/src/ti/map/TiUIMapView.java

### PR DESCRIPTION
**Pull request by mwgarwood**
Update onCameraChange event handler to set the Bearing, Zoom, and Tilt attributes to be available via the map view regionchanged event listener callback.

### CODE REVIEW

**Comment by hansemannn** [comment]
No response from the vendor, closing for now.

**Comment by mwgarwood** [comment]
Can this issue be re-visited?  I submitted a pull-request for the (straight-forward) change some time ago.  Example code would go something like this:

                          var mapview = Map.createView({
			        mapType: Map.SATELLITE_TYPE,
			        region: {latitude: latitude, longitude: longitude, zoom: 15},
			        animate:true,
			        regionFit:true,
			        userLocation: false			        
			    });
                            console.log("Original Bearing," + mapview.region.bearing);
		            console.log("Original Tilt," + mapview.region.tilt);
                            console.log("Original Zoom," + mapview.region.zoom);
                            // alter zoom, bearing and/or tilt on map view
                            console.log("New Bearing," + mapview.region.bearing);
		            console.log("New Tilt," + mapview.region.tilt);
                            console.log("New Zoom," + mapview.region.zoom);

**Comment by hansemannn** [comment]
@mwgarwood We are happy to reopen it if this PR can match the general requirements every PR needs to got through. You can find details above.

**Comment by mwgarwood** [comment]
@hansemannn - I'm afraid I don't fully understand the specifics of what else you need/want here.  Sorry.  Does this request need to be submitted somewhere else?

**Pull request closed without merging**
