### PR TITLE
[TIMOB-18244]: Fixed a couple map crashes

### PR DESCRIPTION
**Pull request by hieupham007**
Testing steps in JIRA

### CODE REVIEW

**Comment by ashcoding** [comment]
Code reviewed. Functionally Tested. 
Travis failing cause it will require the latest master of Ti SDK to compile correctly.

**Comment by ashcoding** [comment]
Manifest min ti sdk should be updated to 4_0_x and above or in the sdk that exactly has the this pr https://github.com/appcelerator/titanium_mobile/pull/6733 backported.

**Comment by ashcoding** [comment]
This https://github.com/appcelerator-modules/ti.map/pull/88 and https://github.com/appcelerator/titanium_mobile/pull/6747 is needed for the travis to pass.

**Comment by hieupham007** [comment]
Updated travis through master.

**Comment by jonalter** [comment]
Travis build passed **accepted**

**Pull request merged**
