### PR TITLE
chore: build with SDK 10.0.1

### PR DESCRIPTION
**Pull request by jquick-axway**
**Summary:**
Modified to build module with Titanium 10.0.1 since iOS minsdk is 10.0.0.

### CODE REVIEW

**Comment by ewanharris** [comment]
It appears that building the test app with 10.0.0.GA is causing the tests to not run. Will look into it today

**Comment by ewanharris** [comment]
Issue looks to be fixed by appcelerator/titanium_mobile/pull/12829, bumping the SDK to `10.0.1.v20210723095034` should fix this

**Comment by jquick-axway** [comment]
This PR isn't done yet. Need to do the following:
- Bring back support for [View.setLocation()](https://titaniumsdk.com/api/modules/map/view.html#setlocation) method.
  * Building with Titanium 10.x.x wrongly turned this into a property, but we document it as a method only.
- Change unit test for `Snapshotter.setShowBuildings()` to use documented `Snapshotter.showBuildings` property instead.

**Comment by hansemannn** [comment]
Would love to see this merged, soon!

**Pull request merged**
