### PR TITLE
Android: Null check in TiMarker

### PR DESCRIPTION
**Pull request by m1ga**
Had this error message during running my app:
```
INFO]  Choreographer: Skipped 74 frames!  The application may be doing too much work on its main thread.
[ERROR] TiExceptionHandler: (main) [66,251578] Attempt to invoke virtual method 'java.lang.String ti.map.AnnotationProxy.getTitle()' on a null object reference
[ERROR] TiExceptionHandler:
[ERROR] TiExceptionHandler:     ti.map.TiMarker.getTitle(TiMarker.java:60)
[ERROR] TiExceptionHandler:     com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.perform(DefaultClusterRenderer.java:835)
[ERROR] TiExceptionHandler:     com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.access$2100(DefaultClusterRenderer.java:805)
[ERROR] TiExceptionHandler:     com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask(DefaultClusterRenderer.java:644)
[ERROR] TiExceptionHandler:     com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage(DefaultClusterRenderer.java:615)
[ERROR] TiExceptionHandler:     android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] TiExceptionHandler:     android.os.Looper.loop(Looper.java:173)
[ERROR] TiExceptionHandler:     android.app.ActivityThread.main(ActivityThread.java:6459)
[ERROR] TiExceptionHandler:     java.lang.reflect.Method.invoke(Native Method)
[ERROR] TiExceptionHandler:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
[ERROR] TiExceptionHandler:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
[INFO]  art: Starting a blocking GC HeapTrim
```
Not sure how it appeared (compiling the app again and it worked fine) but adding a null check around those return statements shouldn't harm.

Trying to see why that error occurred and will add a JIRA ticket

### CODE REVIEW

**Comment by hansemannn** [comment]
+1 for this.

**Comment by jerry42** [comment]
+1 for this too. Had the bug in production app and confirm that a null check fix the bug ;)

**Comment by m1ga** [comment]
Found another section (https://github.com/appcelerator-modules/ti.map/pull/279/files#diff-e32e557cf2aaa9970749dd4d76eca49bR39) that crashed for me earlier today. Added a null check (and clang the file)

**Comment by m1ga** [comment]
Just hit another null error while compiling my app:
```
[ERROR] TiExceptionHandler: (main) [1259,2084] Attempt to read from field 'double com.google.android.gms.maps.model.LatLng.latitude' on a null object reference
[ERROR] TiExceptionHandler:
[ERROR] TiExceptionHandler:     com.google.maps.android.clustering.view.DefaultClusterRenderer$AnimationTask.onAnimationUpdate(DefaultClusterRenderer.java:957)
[ERROR] TiExceptionHandler:     android.animation.ValueAnimator.animateValue(ValueAnimator.java:1558)
[ERROR] TiExceptionHandler:     android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:684)
[ERROR] TiExceptionHandler:     android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:647)
[ERROR] TiExceptionHandler:     android.animation.ValueAnimator.start(ValueAnimator.java:1079)
[ERROR] TiExceptionHandler:     android.animation.ValueAnimator.start(ValueAnimator.java:1098)
[ERROR] TiExceptionHandler:     com.google.maps.android.clustering.view.DefaultClusterRenderer$AnimationTask.perform(DefaultClusterRenderer.java:934)
[ERROR] TiExceptionHandler:     com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask(DefaultClusterRenderer.java:642)
[ERROR] TiExceptionHandler:     com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage(DefaultClusterRenderer.java:615)
[ERROR] TiExceptionHandler:     android.os.Handler.dispatchMessage(Handler.java:107)
[ERROR] TiExceptionHandler:     android.os.Looper.loop(Looper.java:214)
[ERROR] TiExceptionHandler:     android.app.ActivityThread.main(ActivityThread.java:7356)
[ERROR] TiExceptionHandler:     java.lang.reflect.Method.invoke(Native Method)
[ERROR] TiExceptionHandler:     com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[ERROR] TiExceptionHandler:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

fixed here: https://github.com/appcelerator-modules/ti.map/pull/279/commits/78310b9d206ff0e8bff2bf6c31e6a98e182d524d#diff-f3c99af2a7979e334ec513288183b11cR187

**Pull request merged**
