### PR TITLE
MOD-2374: iOS: Ti.Map - Crash when updating multiple annotations

### PR DESCRIPTION
**Pull request by vikas-goyal-axway**
https://jira.appcelerator.org/browse/MOD-2374

### CODE REVIEW

**Comment by vikas-goyal-axway** [comment]
> @vikas-goyal-axway I tried to run with attached test case in ticket. It is crashing for me. Can you recheck your implementation please?
> 
> Did it work for you?

@vijaysingh-axway , I made some changes in pr. Please check it again

**Comment by vijaysingh-axway** [comment]
@vikas-goyal-axway  Changes looks good. Can you update TITANIUM_SDK_VERSION to  9.0.0.GA in titanium.xcconfig.

**Comment by vijaysingh-axway** [comment]
@vikas-goyal-axway Sorry to bother you again.
 We want to release new module version. So please update 
- version in manifest file to 3.3.1.
- version in package.json and package-lock.json to 5.0.2

**Comment by vikas-goyal-axway** [comment]
> @vikas-goyal-axway Sorry to bother you again.
> We want to release new module version. So please update
> 
> * version in manifest file to 3.3.1.
> * version in package.json and package-lock.json to 5.0.2

@vijaysingh-axway , I have added the required changes. Please review it

**Pull request merged**
